# Generated by Django 4.1.3 on 2022-11-24 16:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beachreservation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='umbrellareservation',
            name='number_of_seats',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(4)]),
        ),
    ]
