# Generated by Django 4.1.3 on 2022-11-25 14:20

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beachreservation', '0004_alter_umbrellareservation_reservation_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='umbrellareservation',
            name='reservation_price',
        ),
        migrations.AlterField(
            model_name='umbrellareservation',
            name='reservation_end_date',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date(2022, 11, 25))]),
        ),
        migrations.AlterField(
            model_name='umbrellareservation',
            name='reservation_start_date',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date(2022, 11, 25))]),
        ),
    ]
