# Generated by Django 4.1.3 on 2022-11-25 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beachreservation', '0005_remove_umbrellareservation_reservation_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='umbrellareservation',
            name='reservation_end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='umbrellareservation',
            name='reservation_start_date',
            field=models.DateField(),
        ),
    ]
